require "nokogiri"
require "singleton"
require "string"
require "html_reader"

require "ca/analyse"
require "ca/config"
require "ca/description"
require "ca/features"
require "ca/node_counter"
require "ca/text_analitics"
require "ca/tmp_refactoring"
require "ca/version"
require "ca/warning"

require "ca/exceptions/img_warnings"
require "ca/exceptions/link_warnings"
require "ca/exceptions/tag_warnings"
require "ca/exceptions/title_warnings"

require "nokogiri/HTML/node_specyfication"
require "nokogiri/XML/node"