:a: 1
:abbr: 1
:acronym: 1
:address: 1
:applet: 1
:area: 1
:b: 1
:base: 1
:basefont: 1
:bdo: 1
:big: 1
:blockquote: 1
:body: 1
:br: 1
:button: 1
:caption: 1
:center: 1
:cite: 1
:code: 1
:col: 1
:colgroup: 1
:dd: 1
:del: 1
:dfn: 1
:dir: 1
:div: 1
:dl: 1
:dt: 1
:em: 1
:fieldset: 1
:font: 1
:form: 1
:frame: 1
:frameset: 1
:h1: 1
:h2: 1
:h3: 1
:h4: 1
:h5: 1
:h6: 1
:head: 1
:hr: 1
:html: 1
:i: 1
:iframe: 1
:img: 1
:input: 1
:ins: 1
:isindex: 1
:kbd: 1
:label: 1
:legend: 1
:li: 1
:link: 1
:map: 1
:menu: 1
:meta: 1
:noframes: 1
:noscript: 1
:object: 1
:ol: 1
:optgroup: 1
:option: 1
:p: 1
:param: 1
:pre: 1
:q: 1
:s: 1
:samp: 1
:script: 1
:select: 1
:small: 1
:span: 1
:strike: 1
:strong: 1
:style: 1
:sub: 1
:sup: 1
:table: 1
:tbody: 1
:td: 1
:textarea: 1
:tfoot: 1
:th: 1
:thead: 1
:title: 1
:tr: 1
:tt: 1
:u: 1
:ul: 1
:var: 1
